
include(ExternalProject)
message(STATUS "mnn")

if (ENABLE_NNDEPLOY_INFERENCE_MNN STREQUAL "OFF")
elseif (ENABLE_NNDEPLOY_INFERENCE_MNN STREQUAL "ON")
  message(STATUS "ENABLE_NNDEPLOY_INFERENCE_MNN: ${ENABLE_NNDEPLOY_INFERENCE_MNN}")
else()
  include_directories(${ENABLE_NNDEPLOY_INFERENCE_MNN}/include)
  message(STATUS "include_directories(${ENABLE_NNDEPLOY_INFERENCE_MNN})")
  set(MNN "MNN")
  set(tmp_name ${NNDEPLOY_LIB_PREFIX}${MNN}${NNDEPLOY_LIB_SUFFIX})
  set(tmp_path ${ENABLE_NNDEPLOY_INFERENCE_MNN}/lib/x86/Release)
  if (SYSTEM.Windows)
    # set(tmp_name ${MNN}${NNDEPLOY_LIB_SUFFIX})
    set(tmp_name ${MNN}.lib)
    # set(tmp_path ${ENABLE_NNDEPLOY_INFERENCE_MNN}//lib//x86//Release//)
  endif()
  set(full_name ${tmp_path}/${tmp_name})
  set(NNDEPLOY_THIRD_PARTY_LIBRARY ${NNDEPLOY_THIRD_PARTY_LIBRARY} ${full_name})
  install(FILES ${full_name} DESTINATION ${NNDEPLOY_INSTALL_PATH})
endif()