
include(ExternalProject)
# message(STATUS "ENABLE_NNDEPLOY_INFERENCE_MNN: ${ENABLE_NNDEPLOY_INFERENCE_MNN}")

if (ENABLE_NNDEPLOY_INFERENCE_MNN STREQUAL "OFF")
elseif (ENABLE_NNDEPLOY_INFERENCE_MNN STREQUAL "ON")
else()
  include_directories(${ENABLE_NNDEPLOY_INFERENCE_MNN}/include)
  set(MNN "MNN")
  set(tmp_name ${NNDEPLOY_LIB_PREFIX}${MNN}${NNDEPLOY_LIB_SUFFIX})
  set(tmp_path ${ENABLE_NNDEPLOY_INFERENCE_MNN}/lib)
  set(full_name ${tmp_path}/${tmp_name})
  set(NNDEPLOY_THIRD_PARTY_LIBRARY ${NNDEPLOY_THIRD_PARTY_LIBRARY} ${full_name})
  file(GLOB_RECURSE install_libs "${tmp_path}/*")
  foreach(lib ${install_libs})
    install(FILES ${lib} DESTINATION ${NNDEPLOY_INSTALL_PATH})
  endforeach()
endif()