
include(ExternalProject)

if (ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN STREQUAL "OFF")
elseif (ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN STREQUAL "ON")
else()
  if(IS_ABSOLUTE ${ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN})
    # Absolute path, use directly
    set(ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN ${ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN})
    message(STATUS "Using absolute path for ONEDNN: ${ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN}")
  else()
    # Relative path, relative to project root directory
    set(ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN ${CMAKE_SOURCE_DIR}/${ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN})
    message(STATUS "Using relative path for ONEDNN: ${ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN}")
    # Update ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN to absolute path
    set(ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN ${ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN})
  endif()

  include_directories(${ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN}/include)
  set(LIB_PATH ${ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN}/${NNDEPLOY_THIRD_PARTY_LIBRARY_PATH_SUFFIX})
  set(NNDEPLOY_DEVICE_X86_ONEDNN_LIBS "dnnl") 
  foreach(LIB ${NNDEPLOY_DEVICE_X86_ONEDNN_LIBS})
    set(LIB_NAME ${NNDEPLOY_LIB_PREFIX}${LIB}${NNDEPLOY_LIB_SUFFIX})
    set(FULL_LIB_NAME ${LIB_PATH}/${LIB_NAME})
    if(IS_SYMLINK ${FULL_LIB_NAME})
      get_filename_component(REAL_LIB_NAME ${FULL_LIB_NAME} REALPATH)
      # message(STATUS "Real path of ${FULL_LIB_NAME}: ${REAL_LIB_NAME}")
      set(FULL_LIB_NAME ${REAL_LIB_NAME})
      # message(STATUS "Full lib name: ${FULL_LIB_NAME}")
    endif()
    set(NNDEPLOY_THIRD_PARTY_LIBRARY ${NNDEPLOY_THIRD_PARTY_LIBRARY} ${FULL_LIB_NAME})    
  endforeach()

  if(SYSTEM_Windows)
    set(BIN_PATH ${ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN}/bin)
    link_directories(${BIN_PATH})
  endif()

  # install(DIRECTORY ${ENABLE_NNDEPLOY_DEVICE_X86_ONEDNN} DESTINATION ${NNDEPLOY_INSTALL_THIRD_PARTY_PATH}) 
endif()