include(ExternalProject)

if (ENABLE_NNDEPLOY_INFERENCE_TENSORRT STREQUAL "ON")
  message(STATUS "ENABLE_NNDEPLOY_INFERENCE_TENSORRT: ${ENABLE_NNDEPLOY_INFERENCE_TENSORRT}")
else()
  include_directories(${ENABLE_NNDEPLOY_INFERENCE_TENSORRT}/include)
  include_directories("/home/always/github/nndeploy/third_party/user/linux/tensor_rt/TensorRT-7.2.3.4/include")
  # set(TENSORRT "TENSORRT")
  # set(tmp_name ${NNDEPLOY_LIB_PREFIX}${TENSORRT}${NNDEPLOY_LIB_SUFFIX})
  # if (SYSTEM.Windows)
  #   set(tmp_name ${TENSORRT}${NNDEPLOY_LIB_SUFFIX})
  # endif()
  # set(tmp_path ${ENABLE_NNDEPLOY_INFERENCE_TENSORRT}/lib/x86/Release)
  # set(full_name ${tmp_path}/${tmp_name})
  # set(TMP_THIRD_PARTY_LIBRARY ${TMP_THIRD_PARTY_LIBRARY} ${full_name})
  # install(FILES ${full_name} DESTINATION ${NNDEPLOY_INSTALL_PATH})
endif()