
include(ExternalProject)
# message(STATUS "ENABLE_NNDEPLOY_INFERENCE_TNN: ${ENABLE_NNDEPLOY_INFERENCE_TNN}")

if (ENABLE_NNDEPLOY_INFERENCE_TNN STREQUAL "OFF")
elseif (ENABLE_NNDEPLOY_INFERENCE_TNN STREQUAL "ON")
else()
  include_directories(${ENABLE_NNDEPLOY_INFERENCE_TNN}/include)
  set(TNN "tnn")
  set(tmp_name ${NNDEPLOY_LIB_PREFIX}${TNN}${NNDEPLOY_LIB_SUFFIX})
  set(tmp_path ${ENABLE_NNDEPLOY_INFERENCE_TNN}/lib)
  set(full_name ${tmp_path}/${tmp_name})
  set(NNDEPLOY_THIRD_PARTY_LIBRARY ${NNDEPLOY_THIRD_PARTY_LIBRARY} ${full_name})
  file(GLOB_RECURSE install_libs "${tmp_path}/*")
  foreach(lib ${install_libs})
    install(FILES ${lib} DESTINATION ${NNDEPLOY_INSTALL_PATH})
  endforeach()
endif()