include(ExternalProject)

if (ENABLE_NNDEPLOY_MODEL_TOKENIZER_CPP STREQUAL "OFF")
elseif (ENABLE_NNDEPLOY_MODEL_TOKENIZER_CPP STREQUAL "ON")
  message("tokenizer_cpp is ON")
  set(TOKENZIER_CPP_PATH third_party/tokenizers-cpp)
  add_subdirectory(${TOKENZIER_CPP_PATH} tokenizers)
  include_directories(${TOKENZIER_CPP_PATH}/include)
  set(NNDEPLOY_THIRD_PARTY_LIBRARY ${NNDEPLOY_THIRD_PARTY_LIBRARY} tokenizers_cpp)   
else()
endif()